export {
  MAX_DEEP_DEBUGGING_STEPS,
  createLearningSession,
  applyLearningSessionEvent,
  completeLearningSession,
  toCompletedConceptAssessment,
} from "./lib/session.js";

export type {
  HintDepth,
  ObservationSourceKind,
  ObservationSource,
  ObservationSourceInput,
  Prediction,
  RealityObservation,
  MismatchCategory,
  Mismatch,
  Correction,
  Diagnosis,
  Verification,
  DebuggingStep,
  DebuggingMode,
  CompletedWorkKind,
  CompletedCodingWork,
  CapabilityEvidenceCandidate,
  LearningSession,
  LearningSessionEvent,
  CreateLearningSessionInput,
  StartPredictionInput,
  RecordObservationInput,
  RecordMismatchInput,
  RecordCorrectionInput,
  RecordDiagnosisInput,
  RecordVerificationInput,
  EnterDeepDebuggingInput,
  DebuggingStepInput,
  ExitDeepDebuggingInput,
  RecordCompletedWorkInput,
  CompleteLearningSessionInput,
  CandidateAssessmentInput,
} from "./lib/session.js";
