export const COUNTED_IFC_CLASSES = [
  "IfcWall",
  "IfcWallStandardCase",
  "IfcSlab",
  "IfcRoof",
  "IfcCurtainWall",
  "IfcBuildingElementProxy",
  "IfcRelDefinesByType",
  "IfcRelAssociatesMaterial",
  "IfcRelDefinesByProperties",
  "IfcMaterial",
  "IfcMaterialLayerSetUsage",
  "IfcMaterialLayerSet",
  "IfcMaterialLayer",
  "IfcMaterialConstituentSet",
  "IfcMaterialList",
  "IfcMaterialProfileSetUsage",
  "IfcMaterialProfileSet",
  "IfcWallType",
  "IfcSlabType",
  "IfcRoofType",
  "IfcCurtainWallType",
  "IfcBuildingElementProxyType",
] as const;
