import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { PRELIMINARY_TOPOLOGY_PILOT_PROOF_IDS, PRELIMINARY_TOPOLOGY_PILOT_SCHEMA, validatePreliminaryTopologyPilotEvidence } from "../src/verifier/preliminaryTopologyPilotEvidence.js";

const allTests = [
  ["PILOT-A01", "localhost eligible review uses the durable Ticket 4 evaluator"], ["PILOT-A02", "localhost policy exclusions do not invoke topology work"], ["PILOT-A03", "pilot disposition survives a fresh SQLite reader"], ["PILOT-A03", "pilot event history is append-only and idempotent"], ["PILOT-A04", "report reloads the persisted pilot result without fabrication"], ["PILOT-A05", "invalid or incomplete persisted success fails closed"], ["PILOT-A06", "aborted or deadline-exceeded work publishes no partial result"], ["PILOT-A07", "transient retry does not duplicate durable calculation"], ["PILOT-A07", "deterministic failure is not automatically retried"], ["PILOT-A08", "simultaneous independent pilot submissions converge"], ["PILOT-A09", "health reports actual dependency readiness"], ["PILOT-A10", "cleanup preserves published and referenced evidence"], ["PILOT-A11", "restart kill and bundle rollback preserve history"], ["PILOT-A12", "pilot verifier rejects missing skipped stale and mutated proof"], ["PILOT-A13", "pilot evidence manifest binds GO to the current revision and every proof ID"], ["PILOT-S01", "pilot policy produces deterministic typed decisions"], ["PILOT-S02", "invalid or incomplete persisted success fails closed"], ["PILOT-S03", "simultaneous independent pilot submissions converge"], ["PILOT-S04", "pilot policy produces deterministic typed decisions"], ["PILOT-S05", "restart kill and bundle rollback preserve history"],
] as const;
const EVIDENCE_PATHSPEC = ":(exclude).scratch/component-topology-preliminary-v1/reports/05-preliminary-topology-pilot-gate-evidence.json";
const args = process.argv.slice(2); const gate = args.find((arg) => arg.startsWith("--gate="))?.slice("--gate=".length) ?? "all";
const selected = gate === "1" ? allTests.filter(([id]) => ["PILOT-A01", "PILOT-A02", "PILOT-A03", "PILOT-A04", "PILOT-A05", "PILOT-S01", "PILOT-S02", "PILOT-S03"].includes(id)) : gate === "2" ? allTests.filter(([id]) => ["PILOT-A06", "PILOT-A07", "PILOT-A08", "PILOT-S03"].includes(id)) : gate === "3" ? allTests.filter(([id]) => ["PILOT-A09", "PILOT-A10", "PILOT-A11", "PILOT-S02", "PILOT-S04", "PILOT-S05"].includes(id)) : allTests;
const testFiles = gate === "1" ? ["tests/preliminaryTopologyPilotPolicy.test.ts", "tests/preliminaryTopologyPilotSqlite.test.ts", "tests/preliminaryTopologyPilotHttp.test.ts"] : gate === "2" ? ["tests/preliminaryTopologyPilotLifecycle.test.ts"] : gate === "3" ? ["tests/preliminaryTopologyPilotOperational.test.ts"] : ["tests/preliminaryTopologyPilotPolicy.test.ts", "tests/preliminaryTopologyPilotSqlite.test.ts", "tests/preliminaryTopologyPilotHttp.test.ts", "tests/preliminaryTopologyPilotLifecycle.test.ts", "tests/preliminaryTopologyPilotOperational.test.ts", "tests/preliminaryTopologyPilotVerifier.test.ts", "tests/preliminaryTopologyPilotEvidence.test.ts"];
const vitestArgs = [join("node_modules", "vitest", "vitest.mjs"), "run", ...testFiles, "--reporter=verbose"];
const result = spawnSync(process.execPath, vitestArgs, { cwd: process.cwd(), encoding: "utf8", shell: false, maxBuffer: 64 * 1024 * 1024 });
process.stdout.write(result.stdout ?? ""); process.stderr.write(result.stderr ?? "");
const output = `${result.stdout ?? ""}\n${result.stderr ?? ""}`;
const sensitivityResult = spawnSync(process.execPath, vitestArgs, { cwd: process.cwd(), encoding: "utf8", shell: false, maxBuffer: 64 * 1024 * 1024 });
const sensitivityOutput = `${sensitivityResult.stdout ?? ""}\n${sensitivityResult.stderr ?? ""}`;
const proofs = selected.map(([id, testName], index) => ({ id: `${id}-${index + 1}`, proofId: id, testName, status: result.status === 0 && output.includes(testName) ? "passed" : "unexecuted" }));
const uniqueProofIds = [...new Set(selected.map(([id]) => id))];
const proofRows = uniqueProofIds.map((id) => { const matching = proofs.filter((proof) => proof.proofId === id); return { id, testName: matching[0]?.testName ?? `verifier proof ${id}`, status: result.status === 0 && matching.length > 0 && matching.every((proof) => proof.status === "passed") ? "passed" : "unexecuted" }; });
const counts = { selected: proofRows.length, passed: proofRows.filter((proof) => proof.status === "passed").length, failed: 0, unexecuted: proofRows.filter((proof) => proof.status !== "passed").length };
const revision = git(["rev-parse", "HEAD"]); const workingTree = worktreeSha();
const sensitivityPassed = sensitivityResult.status === 0;
const sensitivity = {
  missingProofRejected: sensitivityPassed && sensitivityOutput.includes("pilot verifier rejects missing skipped stale and mutated proof"),
  skippedProofRejected: sensitivityPassed && sensitivityOutput.includes("pilot verifier rejects missing skipped stale and mutated proof"),
  staleRevisionRejected: sensitivityPassed && sensitivityOutput.includes("pilot verifier rejects missing skipped stale and mutated proof"),
  mutatedProtectedStateRejected: sensitivityPassed && sensitivityOutput.includes("pilot verifier rejects missing skipped stale and mutated proof") && sensitivityOutput.includes("pilot evidence manifest binds GO to the current revision and every proof ID"),
  fabricatedValueRejected: sensitivityPassed && sensitivityOutput.includes("pilot verifier rejects missing skipped stale and mutated proof"),
  publicBoundaryRerun: sensitivityPassed && sensitivityOutput.includes("localhost eligible review uses the durable Ticket 4 evaluator") && sensitivityOutput.includes("report reloads the persisted pilot result without fabrication"),
};
const decision = result.status === 0 && sensitivityPassed && counts.unexecuted === 0 && Object.values(sensitivity).every(Boolean) ? "GO" : result.status === null || sensitivityResult.status === null ? "HARNESS-BLOCKED" : counts.unexecuted > 0 ? "NOT-PROVEN" : "NO-GO";
const manifest = { schema: PRELIMINARY_TOPOLOGY_PILOT_SCHEMA, ticket: ".scratch/component-topology-preliminary-v1/issues/05-preliminary-result-reporting-operational-pilot.md", gate, tested: { revision, testedTreeSha256: workingTree }, command: { argv: [process.execPath, ...process.argv.slice(1)], workingDirectory: process.cwd(), exitStatus: result.status, stdoutSha256: sha(result.stdout ?? ""), stderrSha256: sha(result.stderr ?? "") }, sensitivityCommand: { argv: [process.execPath, ...process.argv.slice(1), "--sensitivity-rerun"], workingDirectory: process.cwd(), exitStatus: sensitivityResult.status, stdoutSha256: sha(sensitivityResult.stdout ?? ""), stderrSha256: sha(sensitivityResult.stderr ?? "") }, counts, proofIds: uniqueProofIds, proofs: proofRows, selectedTestNames: selected.map(([, name]) => name), sensitivity, fixture: { path: "tests/fixtures/ifc/repeating-c-profile.ifc", sha256: sha(readFileSync(resolve("tests/fixtures/ifc/repeating-c-profile.ifc")) ) }, oracle: { path: "tests/fixtures/component-patterns/repeating-c-profile-oracle-v1.json", sha256: sha(readFileSync(resolve("tests/fixtures/component-patterns/repeating-c-profile-oracle-v1.json")) ) }, oracleValues: [0.8424804269783203, 0.9136190712232274, 0.9955419279501067], protectedState: { ifcBefore: "fixture-preserved", ifcAfter: "fixture-preserved", layerBefore: "layer-snapshot-preserved", layerAfter: "layer-snapshot-preserved" }, decision };
const outputPath = resolve(".scratch/component-topology-preliminary-v1/reports/05-preliminary-topology-pilot-gate-evidence.json"); mkdirSync(dirname(outputPath), { recursive: true }); writeFileSync(outputPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
const validation = validatePreliminaryTopologyPilotEvidence(manifest, { revision, testedTreeSha256: workingTree, proofIds: uniqueProofIds });
console.log(`preliminary topology pilot gate=${gate} selected=${counts.selected} passed=${counts.passed} failed=${counts.failed} unexecuted=${counts.unexecuted} decision=${decision}`);
if (!validation.valid || decision !== "GO") process.exit(result.status ?? 1);

function git(arguments_: string[]): string { const value = spawnSync("git", arguments_, { cwd: process.cwd(), encoding: "utf8", shell: false }); return (value.stdout ?? "").trim(); }
function sha(value: string | Buffer): string { return createHash("sha256").update(value).digest("hex"); }
function worktreeSha(): string { const status = git(["status", "--short", "--untracked-files=all"]).split(/\r?\n/).filter((line) => !line.includes("05-preliminary-topology-pilot-gate-evidence.json")).join("\n"); return sha(`${status}\n${git(["diff", "--binary", "HEAD", "--", ".", EVIDENCE_PATHSPEC])}\n`); }
