import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { performance } from "node:perf_hooks";

const cases = [
  ["exact-known", "Exact known promoted match", "known promoted match runs one durable Python scenario"], ["bounded-unknown", "Supported bounded unknown with all three real scenarios", "bounded unknown runs all three durable Python scenarios"], ["conservative-range", "Conservative immaterial range below threshold", "conservative immaterial screening is public and durable"], ["material-range", "Material/crossing range with decisive next input", "restart recomputes the same range from stored scenarios"], ["blocked", "Blocked missing authority/input", "blocked and rejected interpreter outcomes are public and durable"], ["rejected", "Rejected conflicting/out-of-range input or binding", "blocked and rejected interpreter outcomes are public and durable"], ["unmatched", "Unmatched durable unresolved occurrence", "localhost IFC review records unresolved evidence without solving"], ["ambiguous", "Ambiguous promoted candidates", "ambiguous and non-promoted runtime outcomes are public and durable"], ["lifecycle", "Draft/candidate/rejected pattern ignored at runtime", "ambiguous and non-promoted runtime outcomes are public and durable"], ["mixed-terminal", "One scenario non-success with no aggregate range", "one scenario non-success prevents a successful range"], ["duplicates", "Sequential, restarted, retried, and truly simultaneous duplicate submission", "simultaneous duplicate submission publishes one immutable evaluation"], ["replay", "Append-only historical replay", "append-only historical replay crosses public HTTP and fresh reload"], ["corruption", "Corrupted match, Recipe, result, and artifact fail-closed retrieval", "report refuses altered or incomplete success evidence"],
] as const;
const evidenceFields=["publicOutcome","stableDiagnostic","recordIdentities","workerInvocation","artifactHashes","freshReloadOutcome","protectedStateHashes"] as const;
const workerBackedCases=new Set(["exact-known","bounded-unknown","conservative-range","material-range","mixed-terminal","duplicates","corruption"]);
const protectedCases=new Set(["bounded-unknown","mixed-terminal"]);
const started=new Date().toISOString(); const clock=performance.now();
const args=[join("node_modules","vitest","vitest.mjs"),"run","tests/componentScenarioHttpE2e.test.ts","tests/componentOccurrenceHttp.test.ts","tests/componentPatternInterpreter.test.ts","tests/componentEvaluationAggregate.test.ts","tests/componentPatternPromotion.test.ts","tests/componentEvaluationSqlite.test.ts","--reporter=verbose"];
const result=spawnSync(process.execPath,args,{encoding:"utf8",shell:false,maxBuffer:64*1024*1024}); process.stdout.write(result.stdout??""); process.stderr.write(result.stderr??"");
const stdout=result.stdout??""; const outputLines=stdout.split(/\r?\n/);
const caseEvidence=Object.fromEntries([...stdout.matchAll(/CASE_EVIDENCE (\{[^\r\n]+\})/g)].map((match)=>{const value=JSON.parse(match[1]!);return[value.caseId,value]}));
const executedCases=cases.map(([caseId,name,testName])=>{const lines=outputLines.filter((item)=>item.includes(`> ${testName}`));const testPassed=lines.some((item)=>/^[✓√]/u.test(item.trimStart()));const testFailed=lines.some((item)=>/^[×✗]/u.test(item.trimStart()));const evidence=caseEvidence[caseId]??null;const evidenceComplete=validEvidence(caseId,evidence);const status=testFailed?"failed" as const:testPassed&&evidenceComplete?"passed" as const:"unexecuted" as const;return{caseId,name,testName,status,evidence};});
const protectedStateObservations=[...stdout.matchAll(/PROTECTED_STATE (\{[^\r\n]+\})/g)].map((match)=>JSON.parse(match[1]!));
const sensitivity=sensitivityChecks(executedCases,caseEvidence,protectedStateObservations);
const counts={selected:cases.length,passed:executedCases.filter((item)=>item.status==="passed").length,failed:executedCases.filter((item)=>item.status==="failed").length,unexecuted:executedCases.filter((item)=>item.status==="unexecuted").length};
const passed=result.status===0&&counts.passed===cases.length&&counts.failed===0&&counts.unexecuted===0&&Object.values(sensitivity).every(Boolean);
const manifest={schemaVersion:"durable-component-scenario-verifier/v1",startedAt:started,completedAt:new Date().toISOString(),durationMs:Math.round(performance.now()-clock),command:[process.execPath,...args],workingDirectory:process.cwd(),exitStatus:result.status,workerExecutable:process.env.TOPOLOGY_WORKER_PYTHON??".scratch/component-topology-kernel/conformance-proof/.venv/Scripts/python.exe",counts,cases:executedCases,sensitivity,protectedStateObservations,stdoutSha256:sha256(stdout),stderrSha256:sha256(result.stderr??""),decision:passed?"GO":"NO-GO"};
const output=join(".scratch","component-topology-preliminary-v1","reports","09-authoritative-verifier-evidence.json"); mkdirSync(dirname(output),{recursive:true}); writeFileSync(output,JSON.stringify(manifest,null,2)+"\n","utf8"); console.log(`durable-component verifier selected=${counts.selected} passed=${counts.passed} failed=${counts.failed} unexecuted=${counts.unexecuted} decision=${manifest.decision}`); if(!passed)process.exit(result.status??1);

function validEvidence(caseId:string,evidence:any){if(!evidence||!evidenceFields.every((field)=>Object.hasOwn(evidence,field)))return false;if(workerBackedCases.has(caseId)){if(evidence.recordIdentities==="not-applicable"||evidence.workerInvocation==="not-applicable"||evidence.artifactHashes==="not-applicable"||evidence.freshReloadOutcome==="not-applicable")return false;const ids=evidence.recordIdentities;if(!Array.isArray(ids.recipeIds)||!ids.recipeIds.length||!Array.isArray(ids.requestIds)||!ids.requestIds.length||!Array.isArray(ids.resultIds)||!ids.resultIds.length||!Array.isArray(evidence.artifactHashes)||!evidence.artifactHashes.length)return false;}if(protectedCases.has(caseId)&&(typeof evidence.protectedStateHashes!=="object"||evidence.protectedStateHashes.ifcBefore!==evidence.protectedStateHashes.ifcAfter||evidence.protectedStateHashes.layerBefore!==evidence.protectedStateHashes.layerAfter))return false;return true;}
function sensitivityChecks(executed:any[],evidence:Record<string,any>,rows:any[]){const accepts=(e:Record<string,any>,protectedRows:any[])=>{const bounded=e["bounded-unknown"],exact=e["exact-known"],mixed=e["mixed-terminal"],life=e.lifecycle,duplicates=e.duplicates;const oracle=[0.8424804269783203,0.9136190712232274,0.9955419279501067];return executed.every((item)=>item.status==="passed")&&cases.every(([id])=>validEvidence(id,e[id]))&&bounded.scenarioCount===3&&bounded.values.every((value:number,index:number)=>Math.abs(value-oracle[index]!)<=1e-8)&&exact.workerLaunched===true&&JSON.stringify(life.configuredLifecycles)===JSON.stringify(["draft","candidate","rejected"])&&life.lifecycleOutcomes.every((item:any)=>item.outcome==="unmatched"&&item.reloaded)&&life.runtimeMatched===false&&mixed.aggregateRange===false&&duplicates.simultaneous&&duplicates.restarted&&protectedRows.length>=2&&protectedRows.every((row)=>row.ifcBefore===row.ifcAfter&&row.layerBefore===row.layerAfter);};const clone=()=>structuredClone(evidence);const missing=clone();missing["bounded-unknown"].scenarioCount=2;const fabricated=clone();fabricated["bounded-unknown"].values=[0.21,0.24,0.28];const candidate=clone();candidate.lifecycle.runtimeMatched=true;const forbidden=clone();forbidden["mixed-terminal"].aggregateRange=true;const noRestart=clone();noRestart.duplicates.restarted=false;const sequential=clone();sequential.duplicates.simultaneous=false;const noWorker=clone();noWorker["exact-known"].workerLaunched=false;noWorker["exact-known"].workerInvocation="not-applicable";const changedRows=structuredClone(rows);changedRows[0].layerAfter="changed";return{missingScenarioRejected:!accepts(missing,rows),fabricatedValueRejected:!accepts(fabricated,rows),candidateLifecycleRejected:!accepts(candidate,rows),nonSuccessRangeRejected:!accepts(forbidden,rows),protectedMutationRejected:!accepts(evidence,changedRows),skippedRestartClassified:!accepts(noRestart,rows),sequentialConcurrencyClassified:!accepts(sequential,rows),missingWorkerClassified:!accepts(noWorker,rows)};}
function sha256(value:string){return createHash("sha256").update(value).digest("hex");}
