import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ThermalTreatmentAnalysisModel, ThermalTreatmentCalculationWorker, ThermalTreatmentTwoDimensionalBoundary, ThermalTreatmentTwoDimensionalModel, ThermalTreatmentWorkerResult } from "../../domain/thermal-treatment/thermalTreatmentTypes.js";

const workerId = "open-source-finite-difference-2d";
const workerVersion = "1.0.0";
type SolveResult = { uValue: number; totalHeatFlowWPerM: number; converged: boolean };

/** Local, dependency-free finite-difference steady-state 2-D worker. Its public contract is deliberately family-neutral. */
export class OpenSource2dCalculationWorker implements ThermalTreatmentCalculationWorker {
  readonly workerId = workerId;
  readonly workerVersion = workerVersion;
  constructor(private readonly options: { artifactRoot: string } = { artifactRoot: join(process.cwd(), "outputs", "thermal-treatment-worker") }) {}
  async calculate({ analysisModel }: { analysisModel: ThermalTreatmentAnalysisModel }): Promise<ThermalTreatmentWorkerResult> {
    const thermalModel = analysisModel.model.twoDimensionalThermalModel;
    const diagnostics = thermalModel ? validateModel(thermalModel) : ["Analysis model must contain a family-neutral twoDimensionalThermalModel."];
    if (!thermalModel || diagnostics.length) return this.invalid(diagnostics);
    const startedAt = Date.now(), meshes: { x: number; y: number }[] = [], results: SolveResult[] = [];
    try { for (let level = 0; level < thermalModel.solverControls.refinementLevels; level++) { if (Date.now() - startedAt >= thermalModel.solverControls.timeoutMilliseconds) return this.invalid(["2-D thermal calculation timed out before convergence."], meshes); const mesh = meshFor(thermalModel, level); meshes.push(mesh); results.push(solve(thermalModel, mesh, startedAt)); } } catch (error) { return this.invalid([error instanceof Error ? error.message : "2-D thermal worker crashed."], meshes); }
    const latest = results.at(-1)!, previous = results.at(-2); const relativeDifference = previous ? Math.abs(latest.uValue - previous.uValue) / Math.max(Math.abs(latest.uValue), 1e-12) : null;
    const passed = latest.converged && relativeDifference !== null && relativeDifference <= thermalModel.solverControls.convergenceToleranceRelative, convergence = { passed, relativeDifference, refinementLevels: results.length, meshCellCounts: meshes };
    const outputDiagnostics = passed ? [] : [latest.converged ? "Mesh refinement did not meet the requested convergence tolerance." : "2-D solver did not converge within maxIterations."];
    let artifacts: string[] | undefined;
    try { artifacts = await this.writeArtifacts(analysisModel, { uValue: latest.uValue, totalHeatFlowWPerM: latest.totalHeatFlowWPerM, convergence, diagnostics: outputDiagnostics }); } catch (error) { return this.invalid([`Unable to persist reproducibility artifacts: ${error instanceof Error ? error.message : "unknown error"}`], meshes); }
    return { effectiveUValueWPerM2K: latest.uValue, assumptions: ["Steady-state two-dimensional finite-difference conduction model."], provenance: [`${workerId} v${workerVersion}`, "Local in-process open-source TypeScript worker."], validity: { isValid: passed, diagnostics: outputDiagnostics }, numericalResult: { totalHeatFlowWPerM: latest.totalHeatFlowWPerM, effectiveConductanceWPerM2K: latest.uValue, convergence, warnings: [], workerVersions: versions() }, artifactReferences: artifacts };
  }
  private async invalid(diagnostics: string[], meshCellCounts: { x: number; y: number }[] = []): Promise<ThermalTreatmentWorkerResult> { return { effectiveUValueWPerM2K: 1e-12, assumptions: [], provenance: [`${workerId} v${workerVersion}`], validity: { isValid: false, diagnostics }, numericalResult: { totalHeatFlowWPerM: 0, effectiveConductanceWPerM2K: 0, convergence: { passed: false, relativeDifference: null, refinementLevels: meshCellCounts.length, meshCellCounts }, warnings: diagnostics, workerVersions: versions() } }; }
  private async writeArtifacts(analysisModel: ThermalTreatmentAnalysisModel, result: unknown): Promise<string[] | undefined> { const runDirectory = join(this.options.artifactRoot, `${analysisModel.assemblyGroupId}-${Date.now()}`); await mkdir(runDirectory, { recursive: true }); const inputPath = join(runDirectory, "solver-input.json"), resultPath = join(runDirectory, "solver-result.json"); await writeFile(inputPath, JSON.stringify(analysisModel, null, 2)); await writeFile(resultPath, JSON.stringify(result, null, 2)); return [inputPath, resultPath]; }
}
function versions() { return { worker: workerVersion, runtime: process.version, solver: "finite-difference-gauss-seidel" }; }
function validateModel(model: ThermalTreatmentTwoDimensionalModel): string[] { const diagnostics: string[] = []; if (!(model.domain.widthM > 0 && model.domain.heightM > 0)) diagnostics.push("2-D domain widthM and heightM must be positive."); if (!model.regions.length) diagnostics.push("2-D model requires at least one material region."); for (const r of model.regions) if (!r.regionId || !(r.xMinM < r.xMaxM && r.yMinM < r.yMaxM) || r.xMinM < 0 || r.yMinM < 0 || r.xMaxM > model.domain.widthM || r.yMaxM > model.domain.heightM || !(r.conductivityWPerMK > 0)) diagnostics.push(`Region '${r.regionId}' must be inside the domain with positive dimensions and conductivity.`); for (let i = 0; i < model.regions.length; i++) for (const other of model.regions.slice(i + 1)) { const r = model.regions[i]!; if (Math.min(r.xMaxM, other.xMaxM) > Math.max(r.xMinM, other.xMinM) && Math.min(r.yMaxM, other.yMaxM) > Math.max(r.yMinM, other.yMinM)) diagnostics.push(`Regions '${r.regionId}' and '${other.regionId}' overlap.`); } const edges = new Set(model.boundaries.map((b) => b.edge)), periodic = new Set(model.periodicEdges); if (edges.size !== model.boundaries.length) diagnostics.push("Each non-periodic boundary edge must be declared exactly once."); for (const b of model.boundaries) if (!(b.kind === "temperature" ? Number.isFinite(b.temperatureK) : Number.isFinite(b.airTemperatureK) && b.resistanceM2KPerW > 0)) diagnostics.push(`Boundary '${b.boundaryId}' has invalid thermal properties.`); for (const edge of ["left", "right", "top", "bottom"] as const) if (!edges.has(edge) && !periodic.has(edge)) diagnostics.push(`Boundary '${edge}' is neither declared nor periodic.`); if (periodic.has("left") !== periodic.has("right") || periodic.has("top") !== periodic.has("bottom")) diagnostics.push("Periodic boundaries must be declared in opposite pairs."); if (periodic.has("left") || periodic.has("right") || !edges.has("left") || !edges.has("right")) diagnostics.push("This through-wall worker requires declared left and right thermal boundaries; top and bottom may be periodic."); if (!(model.solverControls.maxCellSizeM > 0 && Number.isInteger(model.solverControls.refinementLevels) && model.solverControls.refinementLevels >= 2 && model.solverControls.convergenceToleranceRelative > 0 && model.solverControls.maxIterations > 0 && model.solverControls.timeoutMilliseconds >= 0)) diagnostics.push("Solver controls require positive mesh, tolerance, iteration, timeout values and at least two refinement levels."); return diagnostics; }
function meshFor(model: ThermalTreatmentTwoDimensionalModel, level: number) { const multiple = 2 ** level; return { x: Math.ceil(model.domain.widthM / model.solverControls.maxCellSizeM) * multiple, y: Math.ceil(model.domain.heightM / model.solverControls.maxCellSizeM) * multiple }; }
function solve(model: ThermalTreatmentTwoDimensionalModel, mesh: { x: number; y: number }, startedAt: number): SolveResult { const { x: nx, y: ny } = mesh, dx = model.domain.widthM / nx, dy = model.domain.heightM / ny, k = Array.from({ length: nx * ny }, (_, n) => conductivityAt(model, ((n % nx) + .5) * dx, (Math.floor(n / nx) + .5) * dy)); if (k.some((v) => v === null)) throw new Error("2-D model has uncovered geometry that cannot be meshed."); const t = new Float64Array(nx * ny).fill(meanBoundaryTemperature(model)), index = (i: number, j: number) => j * nx + i; for (let iteration = 0; iteration < model.solverControls.maxIterations; iteration++) { if (Date.now() - startedAt >= model.solverControls.timeoutMilliseconds) throw new Error("2-D thermal calculation timed out before convergence."); let delta = 0; for (let j = 0; j < ny; j++) for (let i = 0; i < nx; i++) { const here = index(i, j), terms: { g: number; t: number }[] = []; add(i-1,j,"left",dx,dy); add(i+1,j,"right",dx,dy); add(i,j-1,"bottom",dy,dx); add(i,j+1,"top",dy,dx); const next = terms.reduce((s,a)=>s+a.g*a.t,0) / terms.reduce((s,a)=>s+a.g,0); delta=Math.max(delta,Math.abs(next-t[here]!)); t[here]=next; function add(ni:number,nj:number,edge:"left"|"right"|"top"|"bottom",distance:number,face:number) { if(ni>=0&&ni<nx&&nj>=0&&nj<ny){const a=index(ni,nj);terms.push({g:harmonic(k[here]!,k[a]!)*face/distance,t:t[a]!});return;} if(model.periodicEdges.includes(edge)){const a=index((ni+nx)%nx,(nj+ny)%ny);terms.push({g:harmonic(k[here]!,k[a]!)*face/distance,t:t[a]!});return;} const b=model.boundaries.find((item)=>item.edge===edge)!;const resistance=distance/(2*k[here]!)+(b.kind==="surface_resistance"?b.resistanceM2KPerW:0);terms.push({g:face/resistance,t:boundaryTemperature(b)}); } } if(delta<1e-8)return heatFlowResult(model,t,k,nx,ny,dx,true); } return heatFlowResult(model,t,k,nx,ny,dx,false); }
function heatFlowResult(model: ThermalTreatmentTwoDimensionalModel, t: Float64Array, k: (number | null)[], nx:number,ny:number,dx:number,converged:boolean):SolveResult { const left=model.boundaries.find((b)=>b.edge==="left")!,right=model.boundaries.find((b)=>b.edge==="right")!,hot=boundaryTemperature(left),cold=boundaryTemperature(right),dy=model.domain.heightM/ny;let q=0;for(let j=0;j<ny;j++){const r=dx/(2*k[j*nx]!)+(left.kind==="surface_resistance"?left.resistanceM2KPerW:0);q+=(hot-t[j*nx]!)/r*dy;}return{totalHeatFlowWPerM:q,uValue:Math.abs(q/(model.domain.heightM*(hot-cold))),converged}; }
function conductivityAt(model: ThermalTreatmentTwoDimensionalModel,x:number,y:number):number|null{return model.regions.find((r)=>x>=r.xMinM&&x<=r.xMaxM&&y>=r.yMinM&&y<=r.yMaxM)?.conductivityWPerMK??null;} function harmonic(a:number,b:number){return 2*a*b/(a+b);} function boundaryTemperature(b:ThermalTreatmentTwoDimensionalBoundary){return b.kind==="temperature"?b.temperatureK:b.airTemperatureK;} function meanBoundaryTemperature(model:ThermalTreatmentTwoDimensionalModel){const all=model.boundaries.map(boundaryTemperature);return all.reduce((s,v)=>s+v,0)/all.length;}



