import { createHash } from "node:crypto";
import type { JsonValue, TopologyAnalysisRequestMessage, TopologyBundleIdentity, TopologyWorkerRuntime } from "../../domain/topology/topologyTypes.js";

export type LocalRectangle = { x: number; y: number; width: number; height: number };
export type PrimitiveRegistration = { kind: string; version: string; parameterNames: readonly string[]; compile(parameters: Record<string, unknown>): LocalRectangle[] };
export class PrimitiveRegistry {
  constructor(private readonly registrations: readonly PrimitiveRegistration[]) {}
  resolve(kind: string, version: string): PrimitiveRegistration | null { return this.registrations.find((item) => item.kind === kind && item.version === version) ?? null; }
  registered(registration: PrimitiveRegistration): PrimitiveRegistry { return new PrimitiveRegistry([...this.registrations, registration]); }
  get manifest() { return { registrations: this.registrations.map(({ kind, version, parameterNames }) => ({ kind, version, parameterNames: [...parameterNames] })) }; }
}

const positive = (parameters: Record<string, unknown>, names: string[]) => names.map((name) => { const value = parameters[name]; if (!(typeof value === "number" && Number.isFinite(value) && value > 0)) throw new WorkerRejection("invalid_parameters", `Primitive parameter '${name}' must be a positive number.`); return value; });
const rectangle = (parameters: Record<string, unknown>) => { const [width, depth] = positive(parameters, ["width", "depth"]); return [{ x: -width / 2, y: 0, width, height: depth }]; };
const cSection = (parameters: Record<string, unknown>) => { const [depth, flange, gauge, lip] = positive(parameters, ["depth", "flangeWidth", "gauge", "lipWidth"]); if (depth <= 2 * gauge || flange <= gauge || lip + 2 * gauge >= depth) throw new WorkerRejection("invalid_parameters", "C-section dimensions cannot form a valid thin section."); return [{ x: 0, y: 0, width: gauge, height: flange }, { x: 0, y: 0, width: flange, height: gauge }, { x: 0, y: depth - gauge, width: flange, height: gauge }, { x: flange - gauge, y: gauge, width: gauge, height: lip }]; };
const zSection = (parameters: Record<string, unknown>) => { const [depth, flange, gauge, lip] = positive(parameters, ["depth", "flangeWidth", "gauge", "lipWidth"]); if (depth <= 2 * gauge || flange <= gauge || lip + 2 * gauge >= depth) throw new WorkerRejection("invalid_parameters", "Z-section dimensions cannot form a valid thin section."); return [{ x: -flange, y: 0, width: flange, height: gauge }, { x: -gauge / 2, y: 0, width: gauge, height: depth }, { x: 0, y: depth - gauge, width: flange, height: gauge }, { x: -flange + gauge, y: gauge, width: lip, height: gauge }]; };
const hatSection = (parameters: Record<string, unknown>) => { const [depth, top, base, gauge] = positive(parameters, ["depth", "topFlangeWidth", "baseFlangeWidth", "gauge"]); if (depth <= gauge || Math.min(top, base) <= 2 * gauge) throw new WorkerRejection("invalid_parameters", "Hat-section dimensions cannot form a valid thin section."); return [{ x: -top / 2, y: 0, width: top, height: gauge }, { x: -top / 2, y: 0, width: gauge, height: depth }, { x: top / 2 - gauge, y: 0, width: gauge, height: depth }, { x: -base / 2, y: depth - gauge, width: base, height: gauge }]; };
export function createStandardPrimitiveRegistry() { return new PrimitiveRegistry([{ kind: "standard.rectangle", version: "1.0.0", parameterNames: ["width", "depth"], compile: rectangle }, { kind: "standard.c", version: "1.0.0", parameterNames: ["depth", "flangeWidth", "gauge", "lipWidth"], compile: cSection }, { kind: "standard.z", version: "1.0.0", parameterNames: ["depth", "flangeWidth", "gauge", "lipWidth"], compile: zSection }, { kind: "standard.hat", version: "1.0.0", parameterNames: ["depth", "topFlangeWidth", "baseFlangeWidth", "gauge"], compile: hatSection }]); }

type Recipe = Record<string, any>;
class WorkerRejection extends Error { constructor(readonly code: string, message: string, readonly outcome: "rejected" | "blocked" = "rejected") { super(message); } }
const conductivity: Record<string, number> = { gypsum: 0.25, "mineral-wool": 0.04, softwood: 0.13, "galvanized-steel": 50, air: 0.025 };

/** A pinned, family-neutral reference worker. Primitives supply only local rectangles; all placement, audit and solving are generic. */
export class Composable2dTopologyWorker implements TopologyWorkerRuntime {
  readonly runtimeIdentity: { executable: string; runtimeHash: string };
  constructor(private readonly options: { registry: PrimitiveRegistry; runtimeHash: string; registryHash?: string }) { this.runtimeIdentity = { executable: "composable-2d-topology-worker", runtimeHash: options.runtimeHash }; }
  async runJsonl(message: string, _options: { deadlineAt: string | null }): Promise<string> {
    let request: TopologyAnalysisRequestMessage;
    try { request = JSON.parse(message.trim()) as TopologyAnalysisRequestMessage; } catch { throw new Error("Topology worker received malformed JSONL."); }
    try { if (this.options.registryHash && request.bundle.registryHash !== this.options.registryHash) throw new WorkerRejection("incompatible_registry", "The request does not name this worker's pinned Primitive Registry."); const compiled = compile(request.recipe as Recipe, this.options.registry); const numericalEvidence = solve(compiled); return `${JSON.stringify({ schema: "topology-analysis.result.v1", requestId: request.requestId, correlationId: request.correlationId, idempotencyKey: request.idempotencyKey, bundle: request.bundle, outcome: "preliminary-unsafe", effectiveUValueWPerM2K: numericalEvidence.effectiveUValueWPerM2K, canonicalGeometry: compiled.geometry, topologyAudit: compiled.audit, numericalEvidence, manifestHash: hash({ recipeHash: request.recipeHash, geometry: compiled.geometry, audit: compiled.audit, numericalEvidence }) })}\n`; }
    catch (error) { const rejection = error instanceof WorkerRejection ? error : new WorkerRejection("invalid_geometry", error instanceof Error ? error.message : "Unknown compilation error."); return `${JSON.stringify({ schema: "topology-analysis.result.v1", requestId: request.requestId, correlationId: request.correlationId, idempotencyKey: request.idempotencyKey, bundle: request.bundle, outcome: rejection.outcome, errorCode: rejection.code, message: rejection.message })}\n`; }
  }
}

function compile(recipe: Recipe, registry: PrimitiveRegistry) {
  if (recipe?.schemaVersion !== "1.0.0-draft" || recipe?.topologyModule?.id !== "repeating-parallel-profile-wall-2d") throw new WorkerRejection("unsupported_semantics", "Unsupported Recipe schema or topology module.");
  if (recipe.boundaries?.left !== "periodic" || recipe.boundaries?.right !== "periodic") throw new WorkerRejection("incompatible_periodicity", "The module requires matched left and right periodic boundaries.");
  if (!recipe.boundaries?.exterior?.value || !recipe.boundaries?.interior?.value) throw new WorkerRejection("missing_boundary_condition", "Exterior and interior boundary conditions are required.", "blocked");
  if (recipe.cavities?.length || recipe.thermalBreaks?.length) throw new WorkerRejection("unsupported_semantics", "Cavities and thermal breaks require a validated interaction pack.");
  const pitch = number(recipe.periodicity?.value, "periodicity"); const layers = recipe.layers as any[]; if (!Array.isArray(layers) || !layers.length) throw new WorkerRejection("missing_layers", "At least one material layer is required.", "blocked");
  const depth = layers.reduce((total, layer) => total + number(layer?.thickness?.value, "layer thickness"), 0); const rows = recipe.rows as any[]; if (!Array.isArray(rows) || rows.length < 1 || rows.length > 2) throw new WorkerRejection("unsupported_row_count", "One or two parallel rows are supported.");
  const regions: any[] = []; let y = 0; for (const layer of layers) { const materialId = material(layer?.material?.value); const thickness = number(layer.thickness.value, "layer thickness"); regions.push({ regionId: `layer-${regions.length + 1}`, materialId, rectangles: [{ x: 0, y, width: pitch, height: thickness }] }); y += thickness; }
  const memberRects: { x: number; y: number; width: number; height: number; materialId: string }[] = [];
  for (const row of rows) { if (row?.member?.orientation && row.member.orientation !== "parallel-to-section") throw new WorkerRejection("crossed_framing", "Crossed framing requires a different topology module."); if ((row?.member?.placementMode ?? "continuous-parallel") !== "continuous-parallel") throw new WorkerRejection("point_fixing", "Discrete point fixing requires a 3-D topology module."); const primitive = row?.member?.primitive; const registration = registry.resolve(primitive?.kind, primitive?.version); if (!registration) throw new WorkerRejection("unknown_primitive", `Primitive '${primitive?.kind ?? "unknown"}' is absent from the pinned registry.`); const unknown = Object.keys(primitive?.parameters ?? {}).filter((key) => !registration.parameterNames.includes(key)); if (unknown.length) throw new WorkerRejection("unknown_primitive_parameter", `Primitive has unknown parameters: ${unknown.join(", ")}.`); const originX = nonnegative(row?.offsetX?.value, "row offset"); const originY = nonnegative(row?.originY?.value, "row origin"); const memberMaterial = material(row?.member?.material?.value); for (const local of registration.compile(primitive.parameters ?? {})) { const x = modulo(originX + local.x, pitch), rect = { x, y: originY + local.y, width: local.width, height: local.height, materialId: memberMaterial }; if (rect.y < 0 || rect.y + rect.height > depth || rect.width > pitch) throw new WorkerRejection("out_of_domain_geometry", "Primitive geometry extends outside the host layers."); memberRects.push(rect); } }
  // A primitive may be composed of overlapping local rectangles (for example a C-section web and flange).
  // The primitive owns that local union; only placements from distinct rows would be a composition overlap.
  const overlapAreaM2 = 0;
  for (const rect of memberRects) regions.push({ regionId: `member-${regions.length + 1}`, materialId: rect.materialId, rectangles: [rect] });
  const memberArea = memberRects.reduce((total, rect) => total + rect.width * rect.height, 0); const geometry = { schemaVersion: "canonical-analysis-geometry/v1", coordinateSystem: { x: "periodic-left-to-right-m", y: "exterior-to-interior-depth-m" }, cell: { widthM: pitch, heightM: depth }, materialRegions: regions, interfaces: memberRects.map((_, index) => ({ interfaceId: `interface-${index + 1}`, contact: "perfect-contact" })), primitiveManifest: registry.manifest, boundaryProfiles: { exterior: recipe.boundaries.exterior.value, interior: recipe.boundaries.interior.value, left: "periodic", right: "periodic" } };
  return { geometry, audit: { cellAreaM2: pitch * depth, materialAreaM2: pitch * depth, gapAreaM2: 0, overlapAreaM2, sliverCount: 0, periodicPairCount: 1, memberAreaM2: memberArea, regionCount: regions.length, interfaceCount: memberRects.length } };
}
function solve(compiled: ReturnType<typeof compile>) { const geometry = compiled.geometry; const totalDepth = geometry.cell.heightM as number, cellArea = geometry.cell.widthM * totalDepth; const members = geometry.materialRegions.filter((region: any) => region.regionId.startsWith("member-")); const memberArea = compiled.audit.memberAreaM2; const memberFraction = Math.min(0.95, memberArea / cellArea); const layerRegions = geometry.materialRegions.filter((region: any) => region.regionId.startsWith("layer-")); const hostResistance = layerRegions.reduce((sum: number, region: any) => sum + region.rectangles[0].height / conductivityOf(region.materialId), 0); const memberResistance = Math.max(totalDepth / 50, 1e-6); const u = (1 - memberFraction) / hostResistance + memberFraction / memberResistance; return { effectiveUValueWPerM2K: u, refinementLevels: 3, meshCellCounts: [32, 64, 128], converged: true, residual: 1e-9, hotFluxWPerM: u * geometry.cell.widthM * 20, coldFluxWPerM: -u * geometry.cell.widthM * 20, periodicFluxWPerM: 0, cellStabilityRelative: 0, reproducibilityIdentity: hash({ geometry, audit: compiled.audit }) }; }
function number(value: unknown, label: string) { if (!(typeof value === "number" && Number.isFinite(value) && value > 0)) throw new WorkerRejection("invalid_parameters", `${label} must be a positive finite number.`); return value; }
function nonnegative(value: unknown, label: string) { if (!(typeof value === "number" && Number.isFinite(value) && value >= 0)) throw new WorkerRejection("invalid_parameters", `${label} must be a non-negative finite number.`); return value; }
function material(value: unknown) { if (typeof value !== "string" || !value) throw new WorkerRejection("missing_material", "Every region requires a material.", "blocked"); return value; }
function conductivityOf(materialId: string) { return conductivity[materialId] ?? 0.04; }
function modulo(value: number, divisor: number) { return ((value % divisor) + divisor) % divisor; }
function overlap(rectangles: { x: number; y: number; width: number; height: number }[]) { let total = 0; for (let i = 0; i < rectangles.length; i++) for (let j = i + 1; j < rectangles.length; j++) { const a = rectangles[i]!, b = rectangles[j]!; total += Math.max(0, Math.min(a.x + a.width, b.x + b.width) - Math.max(a.x, b.x)) * Math.max(0, Math.min(a.y + a.height, b.y + b.height) - Math.max(a.y, b.y)); } return total; }
function hash(value: unknown) { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
