import type { ThermalTreatmentFamilyRegistry } from "../../domain/thermal-treatment/thermalTreatmentTypes.js";
import type { ThermalTreatmentOpportunitySuggestion } from "../../domain/thermal-treatment/detectThermalTreatmentOpportunities.js";
export function buildThermalTreatmentCardModel(command: { suggestions: readonly ThermalTreatmentOpportunitySuggestion[]; registry: ThermalTreatmentFamilyRegistry; assemblyGroupIdsForSuggestion?: (suggestion: ThermalTreatmentOpportunitySuggestion) => string[] }) {
  return command.suggestions.map((suggestion) => {
    const family = command.registry.findByIdentity(suggestion.family);
    if (!family) throw new Error(`Registered Thermal Treatment family is unavailable: ${suggestion.family.familyId}.`);
    const inputs = family.packs.knowledgePack.parameters.filter((input) => input.required && isApplicable(input, suggestion.proposedInputs)).filter((input) => input.key !== "wallLayerStackJson").filter((input) => (suggestion.proposedInputEvidence[input.key]?.status ?? "missing") !== "confirmed").map((input) => ({ key: input.key, label: input.label, unit: input.unit, inputType: input.allowedValues ? "choice" : typeof suggestion.proposedInputs[input.key] === "boolean" ? "boolean" : "number", value: suggestion.proposedInputs[input.key] ?? null, allowedValues: input.allowedValues ?? input.range?.allowedValues ?? [], status: suggestion.proposedInputEvidence[input.key]?.status ?? "missing" }));
    return { suggestionId: suggestion.suggestionId, thermalConstructionSignature: suggestion.thermalConstructionSignature, family: { familyId: suggestion.family.familyId, familyVersion: suggestion.family.familyVersion, label: family.packs.knowledgePack.presentation?.familyLabel ?? suggestion.family.familyId, summary: family.packs.knowledgePack.presentation?.summary ?? "A repeating thermal component was found in the stored IFC evidence." }, affectedElementStepIds: suggestion.affectedElementStepIds, assemblyGroupIds: command.assemblyGroupIdsForSuggestion?.(suggestion) ?? [], affectedWallCount: suggestion.affectedElementStepIds.length, affectedLocations: suggestion.affectedElementNames, matchExplanation: suggestion.reasonCodes, inputs, trustConsequence: "Confirmed critical inputs can produce a Verified result; estimated or missing inputs remain a Preliminary Unsafe Estimate.", advanced: { evidenceReferences: suggestion.evidenceReferences, assumptions: suggestion.assumptions, boundaryConditions: suggestion.boundaryConditions, collapsed: true } };
  });
}
function isApplicable(input: { applicableWhen?: { inputKey: string; equals: unknown } }, values: Record<string, unknown>): boolean { return !input.applicableWhen || values[input.applicableWhen.inputKey] === input.applicableWhen.equals; }